//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vet.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalProcedures
    {
        public int RecordID { get; set; }
        public int AnimalID { get; set; }
        public int ProcedureID { get; set; }
        public System.DateTime ProcedureDate { get; set; }
        public int VeterinarianID { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Procedures Procedures { get; set; }
        public virtual Users Users { get; set; }
    }
}
